brew "gnupg"
brew "pinentry-mac"
brew "ledger"
brew "neovim"
brew "ripgrep"
brew "stow"
brew "tmux"
brew "fzf"
brew "jq"
brew "rsync"
brew "git"
brew "yt-dlp"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "tree"

cask "1password"
cask "iterm2"
cask "maccy"
cask "netnewswire"
cask "omnifocus"
cask "omnigraffle"
cask "tor-browser"
cask "emacs"

cask "font-jetbrains-mono-nerd-font"
