brew "gnupg"
brew "pinentry-mac"
brew "ledger"
brew "neovim"
brew "ripgrep"
brew "stow"
brew "tmux"
brew "universal-ctags"
brew "bat"
brew "fzf"
brew "jq"
brew "fd"

cask "1password"
cask "iterm2"
cask "maccy"
cask "netnewswire"
cask "omnifocus"
cask "omnigraffle"
cask "tor-browser"

cask "font-jetbrains-mono-nerd-font"
