#!/bin/sh

datetime="$(date +'%Y-%m-%d %H:%M')"
keyboard_layout="$(swaymsg -t get_inputs | jq -r '.[] | select(.identifier == "1:1:AT_Translated_Set_2_keyboard") | .xkb_active_layout_name')"

if [ -x $(command -v upower) ]; then
    battery_level="$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage | awk '{print $2}')"
    printf '⌨️ %s |🔋%s | %s' "$keyboard_layout" "$battery_level" "$datetime"
else
    printf '%s | %s' "$keyboard_layout" "$datetime"
fi
